# -*- coding: utf-8 -*-
"""add_two_numbers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pTbYEgFzEPbqfZ9lGz4PnNJJHxQQ6VYa
"""

# Define a function to add two numbers
def add_two_numbers(num1, num2):
    return num1 + num2

# Get input from the user
number1 = float(input("Enter the first number: "))
number2 = float(input("Enter the second number: "))

# Call the function and display the result
result = add_two_numbers(number1, number2)
print(f"The sum of {number1} and {number2} is {result}")